name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4


    - name: compile
      run: gcc fatorial.c function_fatorial.c -o fatorial


    - name: execute
      run: ./fatorial 5


    - name: mostrar o conteúdo do arquivo criado
      run: cat fatorial.txt
